export const ROBINHOOD_TOKENS = [
  {
    symbol: 'BTC',
    name: 'Bitcoin',
    price: 118234.52,
    change24h: 0.37,
    category: 'Layer 1',
    logo: 'https://cryptologos.cc/logos/bitcoin-btc-logo.png',
    description: 'The original cryptocurrency. Bitcoin is a decentralized digital currency that operates on a peer-to-peer network.',
    marketCap: '2.31T',
    volume24h: '42.8B',
    supply: '19.8M BTC',
    high52w: '126,800',
    low52w: '54,200',
  },
  {
    symbol: 'ETH',
    name: 'Ethereum',
    price: 3654.21,
    change24h: 0.21,
    category: 'Layer 1',
    logo: 'https://cryptologos.cc/logos/ethereum-eth-logo.png',
    description: 'Ethereum is a decentralized platform for smart contracts and dApps. ETH is the native currency.',
    marketCap: '439B',
    volume24h: '18.2B',
    supply: '120.2M ETH',
    high52w: '4,891',
    low52w: '1,520',
  },
  {
    symbol: 'SOL',
    name: 'Solana',
    price: 218.45,
    change24h: 1.72,
    category: 'Layer 1',
    logo: 'https://cryptologos.cc/logos/solana-sol-logo.png',
    description: 'Solana is a high-performance blockchain supporting builders around the world.',
    marketCap: '103B',
    volume24h: '5.8B',
    supply: '471M SOL',
    high52w: '294',
    low52w: '82',
  },
  {
    symbol: 'XRP',
    name: 'XRP',
    price: 2.82,
    change24h: 1.21,
    category: 'Payments',
    logo: 'https://cryptologos.cc/logos/xrp-xrp-logo.png',
    description: 'XRP is a digital asset built for payments. It is the native currency of the XRP Ledger.',
    marketCap: '162B',
    volume24h: '3.2B',
    supply: '57.4B XRP',
    high52w: '3.84',
    low52w: '0.42',
  },
  {
    symbol: 'DOGE',
    name: 'Dogecoin',
    price: 0.2845,
    change24h: 1.40,
    category: 'Meme',
    logo: 'https://cryptologos.cc/logos/dogecoin-doge-logo.png',
    description: 'Dogecoin is a cryptocurrency that was created as a joke but has grown into a community-driven project.',
    marketCap: '42.3B',
    volume24h: '2.1B',
    supply: '148.8B DOGE',
    high52w: '0.452',
    low52w: '0.082',
  },
  {
    symbol: 'ADA',
    name: 'Cardano',
    price: 0.82,
    change24h: 2.31,
    category: 'Layer 1',
    logo: 'https://cryptologos.cc/logos/cardano-ada-logo.png',
    description: 'Cardano is a blockchain platform for smart contracts and dApps, built on peer-reviewed research.',
    marketCap: '29.1B',
    volume24h: '1.2B',
    supply: '35.5B ADA',
    high52w: '1.24',
    low52w: '0.28',
  },
  {
    symbol: 'AVAX',
    name: 'Avalanche',
    price: 42.85,
    change24h: 4.63,
    category: 'Layer 1',
    logo: 'https://cryptologos.cc/logos/avalanche-avax-logo.png',
    description: 'Avalanche is an open, programmable smart contracts platform for decentralized applications.',
    marketCap: '17.2B',
    volume24h: '890M',
    supply: '401M AVAX',
    high52w: '65.20',
    low52w: '18.40',
  },
  {
    symbol: 'LINK',
    name: 'Chainlink',
    price: 18.42,
    change24h: 0.17,
    category: 'Oracle',
    logo: 'https://cryptologos.cc/logos/chainlink-link-logo.png',
    description: 'Chainlink is a decentralized oracle network that enables smart contracts to connect to real-world data.',
    marketCap: '11.5B',
    volume24h: '620M',
    supply: '626M LINK',
    high52w: '28.50',
    low52w: '8.20',
  },
  {
    symbol: 'DOT',
    name: 'Polkadot',
    price: 8.92,
    change24h: 2.86,
    category: 'Layer 0',
    logo: 'https://cryptologos.cc/logos/polkadot-dot-logo.png',
    description: 'Polkadot is a multi-chain network that enables different blockchains to transfer messages and value.',
    marketCap: '12.8B',
    volume24h: '580M',
    supply: '1.43B DOT',
    high52w: '14.20',
    low52w: '3.80',
  },
  {
    symbol: 'SHIB',
    name: 'Shiba Inu',
    price: 0.00002845,
    change24h: 1.78,
    category: 'Meme',
    logo: 'https://cryptologos.cc/logos/shiba-inu-shib-logo.png',
    description: 'Shiba Inu is a meme token that emerged as a community-driven project on Ethereum.',
    marketCap: '16.8B',
    volume24h: '1.2B',
    supply: '589.7T SHIB',
    high52w: '0.000045',
    low52w: '0.000008',
  },
  {
    symbol: 'PEPE',
    name: 'Pepecoin',
    price: 0.00001823,
    change24h: 1.55,
    category: 'Meme',
    logo: 'https://cryptologos.cc/logos/pepe-pepe-logo.png',
    description: 'Pepecoin is a meme cryptocurrency based on the Pepe the Frog meme.',
    marketCap: '7.6B',
    volume24h: '2.1B',
    supply: '420.7T PEPE',
    high52w: '0.000028',
    low52w: '0.000004',
  },
  {
    symbol: 'LTC',
    name: 'Litecoin',
    price: 118.42,
    change24h: 1.04,
    category: 'Payments',
    logo: 'https://cryptologos.cc/logos/litecoin-ltc-logo.png',
    description: 'Litecoin is a peer-to-peer cryptocurrency that enables instant, near-zero cost payments.',
    marketCap: '8.9B',
    volume24h: '720M',
    supply: '75M LTC',
    high52w: '145.00',
    low52w: '52.00',
  },
  {
    symbol: 'UNI',
    name: 'Uniswap',
    price: 14.82,
    change24h: 3.50,
    category: 'DeFi',
    logo: 'https://cryptologos.cc/logos/uniswap-uni-logo.png',
    description: 'Uniswap is a decentralized exchange protocol for swapping ERC-20 tokens.',
    marketCap: '8.9B',
    volume24h: '420M',
    supply: '600M UNI',
    high52w: '22.40',
    low52w: '5.80',
  },
  {
    symbol: 'AAVE',
    name: 'Aave',
    price: 385.42,
    change24h: 1.73,
    category: 'DeFi',
    logo: 'https://cryptologos.cc/logos/aave-aave-logo.png',
    description: 'Aave is an open source and non-custodial liquidity protocol for earning interest on deposits.',
    marketCap: '5.8B',
    volume24h: '380M',
    supply: '15M AAVE',
    high52w: '520.00',
    low52w: '120.00',
  },
  {
    symbol: 'COMP',
    name: 'Compound',
    price: 82.45,
    change24h: 0.81,
    category: 'DeFi',
    logo: 'https://cryptologos.cc/logos/compound-comp-logo.png',
    description: 'Compound is an algorithmic, autonomous interest rate protocol for supplying or borrowing assets.',
    marketCap: '680M',
    volume24h: '120M',
    supply: '8.2M COMP',
    high52w: '142.00',
    low52w: '28.00',
  },
  {
    symbol: 'OP',
    name: 'Optimism',
    price: 2.85,
    change24h: 2.21,
    category: 'Layer 2',
    logo: 'https://cryptologos.cc/logos/optimism-op-logo.png',
    description: 'Optimism is a Layer 2 scaling solution for Ethereum using optimistic rollups.',
    marketCap: '3.2B',
    volume24h: '280M',
    supply: '1.12B OP',
    high52w: '4.85',
    low52w: '0.82',
  },
  {
    symbol: 'ARB',
    name: 'Arbitrum',
    price: 1.42,
    change24h: 6.17,
    category: 'Layer 2',
    logo: 'https://cryptologos.cc/logos/arbitrum-arb-logo.png',
    description: 'Arbitrum is a Layer 2 scaling solution for Ethereum using optimistic rollups.',
    marketCap: '4.8B',
    volume24h: '520M',
    supply: '3.38B ARB',
    high52w: '2.42',
    low52w: '0.42',
  },
  {
    symbol: 'SUSHI',
    name: 'SushiSwap',
    price: 1.82,
    change24h: 2.45,
    category: 'DeFi',
    logo: 'https://cryptologos.cc/logos/sushiswap-sushi-logo.png',
    description: 'SushiSwap is a decentralized exchange and automated market maker protocol.',
    marketCap: '420M',
    volume24h: '85M',
    supply: '231M SUSHI',
    high52w: '3.80',
    low52w: '0.52',
  },
  {
    symbol: 'HBAR',
    name: 'Hedera',
    price: 0.1245,
    change24h: 3.25,
    category: 'Layer 1',
    logo: 'https://cryptologos.cc/logos/hedera-hbar-logo.png',
    description: 'Hedera is a decentralized public network for the enterprise economy.',
    marketCap: '4.5B',
    volume24h: '180M',
    supply: '36.1B HBAR',
    high52w: '0.18',
    low52w: '0.04',
  },
  {
    symbol: 'NEAR',
    name: 'NEAR Protocol',
    price: 7.82,
    change24h: 1.85,
    category: 'Layer 1',
    logo: 'https://cryptologos.cc/logos/near-protocol-near-logo.png',
    description: 'NEAR Protocol is a decentralized application platform designed for usability.',
    marketCap: '8.5B',
    volume24h: '420M',
    supply: '1.08B NEAR',
    high52w: '12.40',
    low52w: '2.80',
  },
  {
    symbol: 'XLM',
    name: 'Stellar Lumens',
    price: 0.42,
    change24h: 2.15,
    category: 'Payments',
    logo: 'https://cryptologos.cc/logos/stellar-xlm-logo.png',
    description: 'Stellar is an open network for storing and moving money.',
    marketCap: '12.5B',
    volume24h: '380M',
    supply: '30.1B XLM',
    high52w: '0.68',
    low52w: '0.08',
  },
  {
    symbol: 'XTZ',
    name: 'Tezos',
    price: 1.42,
    change24h: 2.21,
    category: 'Layer 1',
    logo: 'https://cryptologos.cc/logos/tezos-xtz-logo.png',
    description: 'Tezos is a self-amending cryptographic ledger.',
    marketCap: '1.5B',
    volume24h: '65M',
    supply: '1.05B XTZ',
    high52w: '2.40',
    low52w: '0.52',
  },
  {
    symbol: 'BCH',
    name: 'Bitcoin Cash',
    price: 585.42,
    change24h: 0.08,
    category: 'Payments',
    logo: 'https://cryptologos.cc/logos/bitcoin-cash-bch-logo.png',
    description: 'Bitcoin Cash is a peer-to-peer electronic cash system.',
    marketCap: '11.6B',
    volume24h: '420M',
    supply: '19.8M BCH',
    high52w: '780.00',
    low52w: '220.00',
  },
  {
    symbol: 'ETC',
    name: 'Ethereum Classic',
    price: 32.85,
    change24h: 3.17,
    category: 'Layer 1',
    logo: 'https://cryptologos.cc/logos/ethereum-classic-etc-logo.png',
    description: 'Ethereum Classic is an open-source, decentralized computing network.',
    marketCap: '4.8B',
    volume24h: '320M',
    supply: '146M ETC',
    high52w: '52.00',
    low52w: '12.00',
  },
  {
    symbol: 'CRV',
    name: 'Curve DAO',
    price: 0.82,
    change24h: 0.08,
    category: 'DeFi',
    logo: 'https://cryptologos.cc/logos/curve-dao-token-crv-logo.png',
    description: 'Curve is a decentralized exchange for stablecoins using an automated market maker.',
    marketCap: '1.1B',
    volume24h: '180M',
    supply: '1.34B CRV',
    high52w: '2.40',
    low52w: '0.22',
  },
  {
    symbol: 'LDO',
    name: 'Lido DAO',
    price: 2.42,
    change24h: 0.22,
    category: 'DeFi',
    logo: 'https://cryptologos.cc/logos/lido-dao-ldo-logo.png',
    description: 'Lido is a liquid staking solution for Ethereum and other PoS blockchains.',
    marketCap: '2.2B',
    volume24h: '120M',
    supply: '890M LDO',
    high52w: '4.20',
    low52w: '0.82',
  },
  {
    symbol: 'ATOM',
    name: 'Cosmos',
    price: 8.42,
    change24h: 1.45,
    category: 'Layer 0',
    logo: 'https://cryptologos.cc/logos/cosmos-atom-logo.png',
    description: 'Cosmos is an ecosystem of blockchains that can scale and interoperate with each other.',
    marketCap: '3.2B',
    volume24h: '280M',
    supply: '380M ATOM',
    high52w: '15.20',
    low52w: '3.40',
  },
  {
    symbol: 'FIL',
    name: 'Filecoin',
    price: 8.42,
    change24h: 2.15,
    category: 'Storage',
    logo: 'https://cryptologos.cc/logos/filecoin-fil-logo.png',
    description: 'Filecoin is a decentralized storage network for storing data.',
    marketCap: '4.5B',
    volume24h: '320M',
    supply: '534M FIL',
    high52w: '15.80',
    low52w: '2.80',
  },
  {
    symbol: 'RENDER',
    name: 'Render',
    price: 9.42,
    change24h: 1.85,
    category: 'Compute',
    logo: 'https://cryptologos.cc/logos/render-token-render-logo.png',
    description: 'Render Network connects node operators with artists to process GPU rendering.',
    marketCap: '3.8B',
    volume24h: '280M',
    supply: '402M RENDER',
    high52w: '15.80',
    low52w: '2.40',
  },
  {
    symbol: 'GRT',
    name: 'The Graph',
    price: 0.28,
    change24h: 1.45,
    category: 'Indexing',
    logo: 'https://cryptologos.cc/logos/the-graph-grt-logo.png',
    description: 'The Graph is an indexing protocol for querying networks like Ethereum and IPFS.',
    marketCap: '2.8B',
    volume24h: '180M',
    supply: '10.2B GRT',
    high52w: '0.48',
    low52w: '0.08',
  },
  {
    symbol: 'SNX',
    name: 'Synthetix',
    price: 4.82,
    change24h: 2.45,
    category: 'DeFi',
    logo: 'https://cryptologos.cc/logos/synthetix-snx-logo.png',
    description: 'Synthetix is a synthetic asset protocol for creating on-chain synthetic assets.',
    marketCap: '1.5B',
    volume24h: '120M',
    supply: '314M SNX',
    high52w: '8.40',
    low52w: '1.20',
  },
  {
    symbol: 'IMX',
    name: 'Immutable',
    price: 1.82,
    change24h: 1.25,
    category: 'Gaming',
    logo: 'https://cryptologos.cc/logos/immutable-imx-logo.png',
    description: 'Immutable is a Layer 2 scaling solution for NFTs on Ethereum.',
    marketCap: '2.8B',
    volume24h: '180M',
    supply: '1.54B IMX',
    high52w: '3.80',
    low52w: '0.42',
  },
  {
    symbol: 'AXS',
    name: 'Axie Infinity',
    price: 12.42,
    change24h: 1.85,
    category: 'Gaming',
    logo: 'https://cryptologos.cc/logos/axie-infinity-axs-logo.png',
    description: 'Axie Infinity is a blockchain-based trading and battling game.',
    marketCap: '1.8B',
    volume24h: '120M',
    supply: '145M AXS',
    high52w: '22.40',
    low52w: '4.20',
  },
  {
    symbol: 'BAT',
    name: 'Basic Attention Token',
    price: 0.28,
    change24h: 1.45,
    category: 'Utility',
    logo: 'https://cryptologos.cc/logos/basic-attention-token-bat-logo.png',
    description: 'BAT is an Ethereum-based advertising token for the Brave browser.',
    marketCap: '420M',
    volume24h: '85M',
    supply: '1.5B BAT',
    high52w: '0.48',
    low52w: '0.08',
  },
  {
    symbol: 'INJ',
    name: 'Injective',
    price: 28.42,
    change24h: 2.15,
    category: 'DeFi',
    logo: 'https://cryptologos.cc/logos/injective-inj-logo.png',
    description: 'Injective is a blockchain built for finance with MEV-free trading.',
    marketCap: '2.8B',
    volume24h: '220M',
    supply: '98M INJ',
    high52w: '52.00',
    low52w: '8.40',
  },
  {
    symbol: 'FLOKI',
    name: 'Floki',
    price: 0.000285,
    change24h: 1.56,
    category: 'Meme',
    logo: 'https://cryptologos.cc/logos/floki-floki-logo.png',
    description: 'Floki is a meme coin inspired by Elon Musk\'s Shiba Inu.',
    marketCap: '2.8B',
    volume24h: '420M',
    supply: '9.6T FLOKI',
    high52w: '0.00045',
    low52w: '0.00004',
  },
  {
    symbol: 'BONK',
    name: 'BONK',
    price: 0.0000285,
    change24h: 1.65,
    category: 'Meme',
    logo: 'https://cryptologos.cc/logos/bonk-bonk-logo.png',
    description: 'BONK is a Solana-based meme coin.',
    marketCap: '1.8B',
    volume24h: '320M',
    supply: '63T BONK',
    high52w: '0.000045',
    low52w: '0.000004',
  },
  {
    symbol: 'WIF',
    name: 'dogwifhat',
    price: 1.82,
    change24h: 0.00,
    category: 'Meme',
    logo: 'https://cryptologos.cc/logos/dogwifhat-wif-logo.png',
    description: 'dogwifhat is a Solana-based meme coin featuring a Shiba Inu in a pink knitted hat.',
    marketCap: '1.8B',
    volume24h: '420M',
    supply: '998M WIF',
    high52w: '4.85',
    low52w: '0.42',
  },
  {
    symbol: 'PENGU',
    name: 'Pudgy Penguins',
    price: 0.0285,
    change24h: 1.83,
    category: 'NFT',
    logo: 'https://cryptologos.cc/logos/pudgy-penguins-pengu-logo.png',
    description: 'Pudgy Penguins is a collection of 8,888 unique penguins on Ethereum.',
    marketCap: '1.8B',
    volume24h: '280M',
    supply: '62.4B PENGU',
    high52w: '0.045',
    low52w: '0.004',
  },
  {
    symbol: 'PNUT',
    name: 'Peanut the Squirrel',
    price: 1.42,
    change24h: 0.06,
    category: 'Meme',
    logo: 'https://cryptologos.cc/logos/peanut-the-squirrel-pnut-logo.png',
    description: 'Peanut the Squirrel is a meme coin based on the viral internet meme.',
    marketCap: '1.4B',
    volume24h: '280M',
    supply: '999M PNUT',
    high52w: '2.45',
    low52w: '0.12',
  },
  {
    symbol: 'POPCAT',
    name: 'Popcat',
    price: 1.22,
    change24h: 1.75,
    category: 'Meme',
    logo: 'https://cryptologos.cc/logos/popcat-popcat-logo.png',
    description: 'Popcat is a Solana-based meme coin based on the viral Popcat meme.',
    marketCap: '1.2B',
    volume24h: '220M',
    supply: '999M POPCAT',
    high52w: '1.85',
    low52w: '0.08',
  },
  {
    symbol: 'MOODENG',
    name: 'Moo Deng',
    price: 0.28,
    change24h: 0.62,
    category: 'Meme',
    logo: 'https://cryptologos.cc/logos/moo-deng-moodeng-logo.png',
    description: 'Moo Deng is a meme coin based on the viral baby hippo from Thailand.',
    marketCap: '280M',
    volume24h: '85M',
    supply: '999M MOODENG',
    high52w: '0.42',
    low52w: '0.02',
  },
  {
    symbol: 'TRUMP',
    name: 'OFFICIAL TRUMP',
    price: 12.42,
    change24h: 2.15,
    category: 'Meme',
    logo: 'https://cryptologos.cc/logos/official-trump-trump-logo.png',
    description: 'OFFICIAL TRUMP is a meme coin associated with Donald Trump.',
    marketCap: '2.4B',
    volume24h: '420M',
    supply: '199M TRUMP',
    high52w: '18.40',
    low52w: '4.20',
  },
  {
    symbol: 'MEW',
    name: 'cat in a dogs world',
    price: 0.0082,
    change24h: 0.34,
    category: 'Meme',
    logo: 'https://cryptologos.cc/logos/cat-in-a-dogs-world-mew-logo.png',
    description: 'cat in a dogs world is a Solana-based meme coin.',
    marketCap: '720M',
    volume24h: '120M',
    supply: '88.8B MEW',
    high52w: '0.012',
    low52w: '0.002',
  },
  {
    symbol: 'ENA',
    name: 'Ethena',
    price: 0.82,
    change24h: 0.34,
    category: 'DeFi',
    logo: 'https://cryptologos.cc/logos/ethena-ena-logo.png',
    description: 'Ethena is a synthetic dollar protocol built on Ethereum.',
    marketCap: '1.2B',
    volume24h: '180M',
    supply: '1.5B ENA',
    high52w: '1.52',
    low52w: '0.12',
  },
  {
    symbol: 'ONDO',
    name: 'Ondo',
    price: 1.22,
    change24h: 0.00,
    category: 'DeFi',
    logo: 'https://cryptologos.cc/logos/ondo-finance-ondo-logo.png',
    description: 'Ondo Finance is a protocol that builds institutional-grade financial products.',
    marketCap: '1.8B',
    volume24h: '220M',
    supply: '1.5B ONDO',
    high52w: '2.40',
    low52w: '0.22',
  },
  {
    symbol: 'HYPE',
    name: 'Hyperliquid',
    price: 42.85,
    change24h: 1.20,
    category: 'DeFi',
    logo: 'https://cryptologos.cc/logos/hyperliquid-hype-logo.png',
    description: 'Hyperliquid is a decentralized perpetual exchange.',
    marketCap: '14.2B',
    volume24h: '820M',
    supply: '331M HYPE',
    high52w: '58.00',
    low52w: '8.40',
  },
  {
    symbol: 'WLD',
    name: 'Worldcoin',
    price: 2.85,
    change24h: 1.45,
    category: 'Identity',
    logo: 'https://cryptologos.cc/logos/worldcoin-wld-logo.png',
    description: 'Worldcoin is a new globally inclusive identity and financial network.',
    marketCap: '2.1B',
    volume24h: '320M',
    supply: '735M WLD',
    high52w: '4.80',
    low52w: '0.82',
  },
  {
    symbol: 'TON',
    name: 'Toncoin',
    price: 5.82,
    change24h: 0.00,
    category: 'Layer 1',
    logo: 'https://cryptologos.cc/logos/toncoin-ton-logo.png',
    description: 'Toncoin is a decentralized layer-1 blockchain originally designed by Telegram.',
    marketCap: '14.5B',
    volume24h: '280M',
    supply: '2.49B TON',
    high52w: '8.20',
    low52w: '1.80',
  },
  {
    symbol: 'XCN',
    name: 'Onyxcoin',
    price: 0.0185,
    change24h: 0.78,
    category: 'Utility',
    logo: 'https://cryptologos.cc/logos/onyxcoin-xcn-logo.png',
    description: 'Onyxcoin is the native token of the Onyx Protocol.',
    marketCap: '520M',
    volume24h: '85M',
    supply: '28.1B XCN',
    high52w: '0.038',
    low52w: '0.004',
  },
  {
    symbol: 'WLFI',
    name: 'World Liberty Financial',
    price: 0.42,
    change24h: 0.39,
    category: 'DeFi',
    logo: 'https://cryptologos.cc/logos/world-liberty-financial-wlfi-logo.png',
    description: 'World Liberty Financial is a DeFi protocol backed by Donald Trump.',
    marketCap: '1.8B',
    volume24h: '180M',
    supply: '4.2B WLFI',
    high52w: '0.82',
    low52w: '0.08',
  },
  {
    symbol: 'ZORA',
    name: 'Zora',
    price: 0.28,
    change24h: 0.85,
    category: 'NFT',
    logo: 'https://cryptologos.cc/logos/zora-zora-logo.png',
    description: 'Zora is a decentralized protocol for creating and collecting onchain media.',
    marketCap: '280M',
    volume24h: '45M',
    supply: '1B ZORA',
    high52w: '0.42',
    low52w: '0.04',
  },
  {
    symbol: 'VIRTUAL',
    name: 'Virtuals Protocol',
    price: 2.42,
    change24h: 2.96,
    category: 'AI',
    logo: 'https://cryptologos.cc/logos/virtuals-protocol-virtual-logo.png',
    description: 'Virtuals Protocol is a platform for AI agents on blockchain.',
    marketCap: '1.8B',
    volume24h: '280M',
    supply: '1B VIRTUAL',
    high52w: '5.20',
    low52w: '0.22',
  },
  {
    symbol: 'SYRUP',
    name: 'Maple Finance',
    price: 0.82,
    change24h: 1.56,
    category: 'DeFi',
    logo: 'https://cryptologos.cc/logos/maple-finance-syrup-logo.png',
    description: 'Maple Finance is an institutional capital marketplace.',
    marketCap: '280M',
    volume24h: '45M',
    supply: '341M SYRUP',
    high52w: '1.42',
    low52w: '0.12',
  },
  {
    symbol: 'PAXG',
    name: 'Pax Gold',
    price: 3685.42,
    change24h: 0.42,
    category: 'Commodity',
    logo: 'https://cryptologos.cc/logos/pax-gold-paxg-logo.png',
    description: 'Pax Gold is a digital asset backed by physical gold.',
    marketCap: '1.2B',
    volume24h: '85M',
    supply: '325K PAXG',
    high52w: '4,200',
    low52w: '1,800',
  },
  {
    symbol: 'ZEC',
    name: 'Zcash',
    price: 68.42,
    change24h: 1.85,
    category: 'Privacy',
    logo: 'https://cryptologos.cc/logos/zcash-zec-logo.png',
    description: 'Zcash is a cryptocurrency with strong privacy features.',
    marketCap: '1.1B',
    volume24h: '120M',
    supply: '16.2M ZEC',
    high52w: '120.00',
    low52w: '22.00',
  },
];

export const TOKEN_CATEGORIES = [
  { id: 'all', name: 'All', icon: '🔥' },
  { id: 'Layer 1', name: 'Layer 1', icon: '⛓️' },
  { id: 'Layer 2', name: 'Layer 2', icon: '⚡' },
  { id: 'DeFi', name: 'DeFi', icon: '🏦' },
  { id: 'Meme', name: 'Meme', icon: '🐸' },
  { id: 'Payments', name: 'Payments', icon: '💳' },
  { id: 'NFT', name: 'NFT', icon: '🖼️' },
  { id: 'AI', name: 'AI', icon: '🤖' },
  { id: 'Gaming', name: 'Gaming', icon: '🎮' },
  { id: 'Storage', name: 'Storage', icon: '💾' },
  { id: 'Privacy', name: 'Privacy', icon: '🔒' },
  { id: 'Commodity', name: 'Gold', icon: '🥇' },
];

export function getTokenBySymbol(symbol) {
  return ROBINHOOD_TOKENS.find(t => t.symbol === symbol);
}

export function filterRobinhoodTokens(query) {
  const q = (query || '').trim().toLowerCase();
  if (!q) return ROBINHOOD_TOKENS;
  return ROBINHOOD_TOKENS.filter(
    t =>
      t.symbol.toLowerCase().includes(q) ||
      t.name.toLowerCase().includes(q) ||
      t.category.toLowerCase().includes(q)
  );
}

export function getTokensByCategory(category) {
  if (category === 'all') return ROBINHOOD_TOKENS;
  return ROBINHOOD_TOKENS.filter(t => t.category === category);
}
